# -*- coding: utf-8 -*-
"""Assignment_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LJrUDC1JIwfJ5NzCzCWOdPHkH3Rgb1zK

Problem Statement: Write a Python program that:
1.   Defines a function named factorial that takes a number as an argument and calculates its factorial using a loop or recursion.
2.   Returns the calculated factorial.
3.   Calls the function with a sample number and prints the output.
"""

def Factorial(n):
  if(n>=2):
    return n*Factorial(n-1)
  else:
    return 1
try:
  userInput = int(input("Enter the number: "))
  result = Factorial(userInput)
  print(f'Factorial of {userInput} is {result}')
except ValueError:
  print("Your input is incorrect, please enter valid number")

"""Task 2: Using the Math Module for Calculations

Problem Statement: Write a Python program that:
1.   Asks the user for a number as input.
2.   Uses the math module to calculate the:
  o   Square root of the number
  o   Natural logarithm (log base e) of the number
  o   Sine of the number (in radians)
3.   Displays the calculated results.

"""

try:
  userInput1 = int(input("Enter the number: "))
except ValueError:
  print("Your input is incorrect, please enter correct number")
import math
def squareRoot(n):
  return math.sqrt(n)
def natLog(n):
  return math.log(n)
def sine(n):
  return math.sin(n)

result1 = squareRoot(userInput1)
result2 = natLog(userInput1)
result3 = sine(userInput1)

print(f'Square root : {result1}')
print(f'Natural logarithm : {result2}')
print(f'Sine : {result3}')